# Generated by Django 5.2.5 on 2025-08-27 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('choices', models.CharField(choices=[('technology', 'Tecnologia'), ('development', 'Desenvolvimento'), ('ai', 'Inteligência Artificial'), ('science', 'Ciência'), ('education', 'Educação'), ('tutorials', 'Tutoriais'), ('productivity', 'Produtividade'), ('gaming', 'Games'), ('movies', 'Filmes e Séries'), ('books', 'Livros'), ('health', 'Saúde'), ('travel', 'Viagens'), ('finance', 'Finanças'), ('entrepreneurship', 'Empreendedorismo'), ('news', 'Notícias'), ('opinion', 'Opinião')], max_length=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
