# Generated by Django 5.2.5 on 2025-08-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='choices',
            new_name='category',
        ),
    ]
