# Generated by Django 5.2.5 on 2025-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
